name: Reuable Workflow
on:
    workflow_call:
       inputs:
          name:
          description: Enter the name
          required: true
          typw: string

jobs:
    greeting:
        runs-on: ubuntu-latest
        steps:
             - name: Greeting step
               run: echo "Hi ${{ inputs.name }} welcome to reusable workflow!"